SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

BACKGROUND_IMAGE_PATH = "images/game-background.png"
BACKGROUND_OPACITY = 120
MENU_BACKGROUND_IMAGE_PATH = "images/menu-background.png"
MENU_BACKGROUND_OPACITY = 255
GAME_OVER_BACKGROUND_IMAGE_PATH = "images/game-over.png"
GAME_OVER_BACKGROUND_OPACITY = 255
GAME_BORDER_IMAGE_PATH = "images/game-border.png"
GAME_BORDER_OVERFLOW_PX = 28
GAME_VIEW_PADDING_X = 56
GAME_VIEW_PADDING_Y = 36

LINE_WIDTH = 2
SHOT_RADIUS = 5
SHOT_LIFETIME_SECONDS = 1.5
SHOT_SPRITE_PATH = "sprites/missile.png"
SHOT_SPRITE_SIZE_MULTIPLIER = 5.8

PLAYER_RADIUS = 20
PLAYER_ACCELERATION = 280
PLAYER_MAX_SPEED = 340
PLAYER_TURN_SPEED = 300
PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_SPRITE_PATH = "sprites/ship.png"
PLAYER_SPRITE_SIZE_MULTIPLIER = 3.4
PLAYER_INVULNERABLE_SPRITE_PATH = None
PLAYER_INVULNERABLE_DURATION_SECONDS = 3
PLAYER_MAX_HEALTH = 3
PLAYER_BUZZ_AMPLITUDE_PX = 1.4
PLAYER_BUZZ_FREQUENCY_HZ = 9.0
PLAYER_BUZZ_RAMP_UP = 14.0
PLAYER_BUZZ_RAMP_DOWN = 8.0

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

ASTEROID_SPRITE_GLOB = "sprites/asteroid-*.png"
ASTEROID_SPRITE_SCALE_TO_RADIUS = 2.1

EXPLOSION_GIF_PATH = "images/explosion.gif"
EXPLOSION_FPS = 28
EXPLOSION_SCALE_TO_RADIUS = 2.8
EXPLOSION_FALLBACK_DURATION_SECONDS = 0.42
