SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

BACKGROUND_IMAGE_PATH = "images/game-background.png"
BACKGROUND_OPACITY = 80

LINE_WIDTH = 2
SHOT_RADIUS = 5
SHOT_LIFETIME_SECONDS = 1.5
SHOT_SPRITE_PATH = "sprites/missile.png"
SHOT_SPRITE_SIZE_MULTIPLIER = 5.2

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_SPRITE_PATH = "sprites/ship.png"
PLAYER_SPRITE_SIZE_MULTIPLIER = 3.4

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

ASTEROID_SPRITE_GLOB = "sprites/asteroid-*.png"
ASTEROID_SPRITE_SCALE_TO_RADIUS = 2.1
